### PR TITLE
Fix "content-length required" error.

### LINKED ISSUE #32: Error signing in to vuiet
After many months of successful use of vuiet I suddenly cannot access vuiet in emacs. When I try to play loved tracks I get the following error:
Play random? (y or n) y
[error] request--callback: peculiar error: 411
[error] request-default-error-callback: http://ws.audioscrobbler.com/2.0/ error

Can you help me figure out why I am getting this error?

I am using doom emacs which uses emacs 27.1

Not sure if this is related but I also am getting error message upon starting doom emacs that the cL library is deprecated.  Apparently vuiet uses cl (which is to be replaced by cl-lib) see https://github.com/hlissner/doom-emacs/issues/3372

### PR DESCRIPTION
**Pull request by aluaces**
This intends to fix https://github.com/mihaiolteanu/vuiet/issues/32 

However, since request-curl-options is a list, maybe the appropriate is to try to add this option to a possibly existing one instead of just overwriting it.

### CODE REVIEW

**Comment by mihaiolteanu** [comment]
Depends. Maybe we only want these options, maybe not. Anyway, `request-curl-options` is `nil` by default, so adding to it would only make sense if you would modify it multiple times in the same form, which is not our case. I would say it's good the way you've set it.

I've tested your modified `request-curl-options`, and it works, but not in the format that you've committed. Can you spot the error?
 
I've also tried at least one last.fm call that requires authentication, like `(lastfm-track-love "anathema" "springfield")`, for example, and that still doesn't work. Does it work on your side? Maybe it's the same error, maybe something different, I haven't check it out yet. Anyway, even without this, it's still a big improvement over the previous state, since the majority of calls don't require authentication (those that don't actually change something on the site, but just get info from it).

**Comment by aluaces** [comment]
> Depends. Maybe we only want these options, maybe not. Anyway, `request-curl-options` is `nil` by default, so adding to it would only make sense if you would modify it multiple times in the same form, which is not our case. I would say it's good the way you've set it.

I wanted to refer to the case in which the user has already set that variable, for example, in order to point to a proxy.  With the current form, we would wipe their preferences, although only for lastfm.el, indeed.

> I've tested your modified `request-curl-options`, and it works, but not in the format that you've committed. Can you spot the error?

Ok, nice quiz ;-D give me some time for catching it!

> I've also tried at least one last.fm call that requires authentication, like `(lastfm-track-love "anathema" "springfield")`, for example, and that still doesn't work. Does it work on your side? Maybe it's the same error, maybe something different, I haven't check it out yet. Anyway, even without this, it's still a big improvement over the previous state, since the majority of calls don't require authentication (those that don't actually change something on the site, but just get info from it).

Now that you mention, I'm not sure if I tried.  I have to investigate further if both problems are related or not.

**Comment by mihaiolteanu** [comment]
> I wanted to refer to the case in which the user has already set that variable, for example, in order to point to a proxy. With the current form, we would wipe their preferences, although only for lastfm.el, indeed.

True. That could be another exercise, then, if you want. Whichever way you think it's best.

> I've tested your modified request-curl-options, and it works, but not in the format that you've committed. Can you spot the error?

Oh, yes, it works, my bad. I was thinking of something like this,

```
(let ((request-curl-options (cons "-d\"\"" request-curl-options))
      (resp))
...
```
I got confused by that let form. It's perfectly fine! My bad!

Let me know if you want to add something else. If not, I will merge it.
Good job!

**Comment by mihaiolteanu** [comment]
Any updates, Alberto?

**Comment by aluaces** [comment]
Yes, I can confirm anything related with authentication does not work, but I have yet to know why: the error is different (400) this time, that means a malformed request.

Either it is true and it is a different thing, or either curl is still sending a partial message and results in this new error.

I can have a bash at it in the weekend to see what is happening.

**Comment by mihaiolteanu** [comment]
Yes, I get this

```
[error] request--callback: peculiar error: 400
[error] request-default-error-callback: http://ws.audioscrobbler.com/2.0/ error

Result: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<lfm status=\"failed\">\n  <error code=\"13\">Invalid method signature supplied</error>\n</lfm>\n"
```

Who knows if last.fm didn't change something since all stuff that worked, now doesn't.

This is the documentation for how to sign calls,
https://www.last.fm/api/authspec#_8-signing-calls

**Comment by aluaces** [comment]
> Who knows if last.fm didn't change something since all stuff that worked, now doesn't.
> 
> This is the documentation for how to sign calls,
> https://www.last.fm/api/authspec#_8-signing-calls

That was my first impression, but after that I think that should they do that, they would have to bump the API version.  The other possibility is that they *tolerated* some slight deviation from the documentation and now they are strict, but I have not taken a look at it yet.

**Comment by aluaces** [comment]
I have still not traced the issue, but copying and pasting the URL generated by lastfm.el and using into a curl command

    curl -X POST -d "" <URL>

works perfectly, so the API code has no flaws.  It is a pity that I have not yet managed to see what is the exact incantation that request.el does in order to compare with mine.  So far I activated tracing, but it shows the arguments, not the command invocation as far as I know.

**Comment by mihaiolteanu** [comment]
This will at least fix the non-authentication last.fm methods, at least.
If you find anything else for the authentication methods, you can open another PR/issue/etc.

**Pull request merged**
